[2024-10-07T23:55:14.192-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T23:55:14.218-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:55:12.766760+00:00 [queued]>
[2024-10-07T23:55:14.229-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:55:12.766760+00:00 [queued]>
[2024-10-07T23:55:14.231-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-07T23:55:14.244-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonVirtualenvOperator): preprocess> on 2024-10-08 02:55:12.766760+00:00
[2024-10-07T23:55:14.251-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=223) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T23:55:14.252-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T02:55:12.766760+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpl6qdnuq5']
[2024-10-07T23:55:14.252-0300] {standard_task_runner.py:63} INFO - Started process 224 to run task
[2024-10-07T23:55:14.253-0300] {standard_task_runner.py:91} INFO - Job 100: Subtask preprocess
[2024-10-07T23:55:14.299-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:55:12.766760+00:00 [running]> on host 4a07270c49a4
[2024-10-07T23:55:14.393-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T02:55:12.766760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T02:55:12.766760+00:00'
[2024-10-07T23:55:14.395-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T23:55:14.396-0300] {baseoperator.py:399} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-10-07T23:55:14.398-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvqsn3conm --python=python
[2024-10-07T23:55:14.399-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:55:15.009-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 187ms
[2024-10-07T23:55:15.010-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvqsn3conm, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T23:55:15.011-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T23:55:15.012-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T23:55:15.013-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T23:55:15.038-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvqsn3conm/bin/pip install -r /tmp/venvqsn3conm/requirements.txt
[2024-10-07T23:55:15.039-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:55:16.426-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venvqsn3conm/requirements.txt (line 1))
[2024-10-07T23:55:16.428-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-07T23:55:16.663-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venvqsn3conm/requirements.txt (line 2))
[2024-10-07T23:55:16.665-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T23:55:16.853-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venvqsn3conm/requirements.txt (line 3))
[2024-10-07T23:55:16.855-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-07T23:55:17.006-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvqsn3conm/requirements.txt (line 4))
[2024-10-07T23:55:17.008-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-07T23:55:17.052-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvqsn3conm/requirements.txt (line 3))
[2024-10-07T23:55:17.054-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-07T23:55:17.118-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvqsn3conm/requirements.txt (line 3))
[2024-10-07T23:55:17.120-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-07T23:55:17.150-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venvqsn3conm/requirements.txt (line 3))
[2024-10-07T23:55:17.152-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-07T23:55:17.305-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvqsn3conm/requirements.txt (line 4))
[2024-10-07T23:55:17.306-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T23:55:17.347-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvqsn3conm/requirements.txt (line 4))
[2024-10-07T23:55:17.349-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-07T23:55:17.376-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvqsn3conm/requirements.txt (line 3))
[2024-10-07T23:55:17.378-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-07T23:55:17.393-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-07T23:55:17.395-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-07T23:55:17.413-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-07T23:55:17.427-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-07T23:55:17.442-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-07T23:55:17.444-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-07T23:55:17.446-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-07T23:55:17.492-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-07T23:55:17.493-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-07T23:55:17.495-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-07T23:55:17.683-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-07T23:55:31.385-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-07T23:55:31.780-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.780-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.781-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.782-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.782-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.783-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.784-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.784-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-07T23:55:31.797-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvqsn3conm/bin/python /tmp/venv-callehh8amqf/script.py /tmp/venv-callehh8amqf/script.in /tmp/venv-callehh8amqf/script.out /tmp/venv-callehh8amqf/string_args.txt /tmp/venv-callehh8amqf/termination.log
[2024-10-07T23:55:31.799-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:55:33.103-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-07T23:55:33.104-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callehh8amqf/script.py", line 75, in <module>
[2024-10-07T23:55:33.105-0300] {process_utils.py:191} INFO -     res = task_preprocess(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-07T23:55:33.106-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T23:55:33.106-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callehh8amqf/script.py", line 22, in task_preprocess
[2024-10-07T23:55:33.107-0300] {process_utils.py:191} INFO -     ti = kwargs['ti']
[2024-10-07T23:55:33.107-0300] {process_utils.py:191} INFO -          ~~~~~~^^^^^^
[2024-10-07T23:55:33.107-0300] {process_utils.py:191} INFO - KeyError: 'ti'
[2024-10-07T23:55:33.519-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T23:55:33.532-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'ti'
[2024-10-07T23:55:33.536-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T02:55:12.766760+00:00, execution_date=20241008T025512, start_date=20241008T025514, end_date=20241008T025533
[2024-10-07T23:55:33.556-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task preprocess (Process returned non-zero exit status 1.
'ti'; 224)
[2024-10-07T23:55:33.593-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T23:55:33.614-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T23:55:33.619-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
