[2024-10-07T22:09:35.151-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T22:09:35.223-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T01:09:21.917101+00:00 [queued]>
[2024-10-07T22:09:35.261-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T01:09:21.917101+00:00 [queued]>
[2024-10-07T22:09:35.263-0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-07T22:09:35.304-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocess> on 2024-10-08 01:09:21.917101+00:00
[2024-10-07T22:09:35.319-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T22:09:35.321-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T01:09:21.917101+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpdkqbuvy6']
[2024-10-07T22:09:35.324-0300] {standard_task_runner.py:63} INFO - Started process 2150 to run task
[2024-10-07T22:09:35.324-0300] {standard_task_runner.py:91} INFO - Job 58: Subtask preprocess
[2024-10-07T22:09:35.389-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T01:09:21.917101+00:00 [running]> on host 4a07270c49a4
[2024-10-07T22:09:35.500-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T01:09:21.917101+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T01:09:21.917101+00:00'
[2024-10-07T22:09:35.501-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T22:09:35.503-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvjs4b4_r6 --python=python
[2024-10-07T22:09:35.505-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T22:09:36.205-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 204ms
[2024-10-07T22:09:36.207-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvjs4b4_r6, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T22:09:36.208-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T22:09:36.209-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T22:09:36.210-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T22:09:36.241-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvjs4b4_r6/bin/pip install -r /tmp/venvjs4b4_r6/requirements.txt
[2024-10-07T22:09:36.242-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T22:09:37.612-0300] {process_utils.py:191} INFO - Collecting *** (from -r /tmp/venvjs4b4_r6/requirements.txt (line 1))
[2024-10-07T22:09:37.614-0300] {process_utils.py:191} INFO -   Using cached ***-0.6.tar.gz (1.2 kB)
[2024-10-07T22:09:37.619-0300] {process_utils.py:191} INFO -   Installing build dependencies: started
[2024-10-07T22:09:39.786-0300] {process_utils.py:191} INFO -   Installing build dependencies: finished with status 'done'
[2024-10-07T22:09:39.787-0300] {process_utils.py:191} INFO -   Getting requirements to build wheel: started
[2024-10-07T22:09:40.482-0300] {process_utils.py:191} INFO -   Getting requirements to build wheel: finished with status 'error'
[2024-10-07T22:09:40.487-0300] {process_utils.py:191} INFO -   error: subprocess-exited-with-error
[2024-10-07T22:09:40.489-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:40.489-0300] {process_utils.py:191} INFO -   × Getting requirements to build wheel did not run successfully.
[2024-10-07T22:09:40.490-0300] {process_utils.py:191} INFO -   │ exit code: 1
[2024-10-07T22:09:40.491-0300] {process_utils.py:191} INFO -   ╰─> [26 lines of output]
[2024-10-07T22:09:40.491-0300] {process_utils.py:191} INFO -       running egg_info
[2024-10-07T22:09:40.492-0300] {process_utils.py:191} INFO -       writing ***.egg-info/PKG-INFO
[2024-10-07T22:09:40.493-0300] {process_utils.py:191} INFO -       writing dependency_links to ***.egg-info/dependency_links.txt
[2024-10-07T22:09:40.493-0300] {process_utils.py:191} INFO -       writing top-level names to ***.egg-info/top_level.txt
[2024-10-07T22:09:40.494-0300] {process_utils.py:191} INFO -       reading manifest file '***.egg-info/SOURCES.txt'
[2024-10-07T22:09:40.495-0300] {process_utils.py:191} INFO -       writing manifest file '***.egg-info/SOURCES.txt'
[2024-10-07T22:09:40.495-0300] {process_utils.py:191} INFO -       Traceback (most recent call last):
[2024-10-07T22:09:40.496-0300] {process_utils.py:191} INFO -         File "/tmp/venvjs4b4_r6/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[2024-10-07T22:09:40.496-0300] {process_utils.py:191} INFO -           main()
[2024-10-07T22:09:40.497-0300] {process_utils.py:191} INFO -         File "/tmp/venvjs4b4_r6/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[2024-10-07T22:09:40.497-0300] {process_utils.py:191} INFO -           json_out['return_val'] = hook(**hook_input['kwargs'])
[2024-10-07T22:09:40.498-0300] {process_utils.py:191} INFO -                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T22:09:40.499-0300] {process_utils.py:191} INFO -         File "/tmp/venvjs4b4_r6/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[2024-10-07T22:09:40.499-0300] {process_utils.py:191} INFO -           return hook(config_settings)
[2024-10-07T22:09:40.500-0300] {process_utils.py:191} INFO -                  ^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T22:09:40.500-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-75966q3h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
[2024-10-07T22:09:40.501-0300] {process_utils.py:191} INFO -           return self._get_build_requires(config_settings, requirements=[])
[2024-10-07T22:09:40.502-0300] {process_utils.py:191} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T22:09:40.502-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-75966q3h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
[2024-10-07T22:09:40.503-0300] {process_utils.py:191} INFO -           self.run_setup()
[2024-10-07T22:09:40.504-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-75966q3h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
[2024-10-07T22:09:40.504-0300] {process_utils.py:191} INFO -           super().run_setup(setup_script=setup_script)
[2024-10-07T22:09:40.505-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-75966q3h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
[2024-10-07T22:09:40.506-0300] {process_utils.py:191} INFO -           exec(code, locals())
[2024-10-07T22:09:40.507-0300] {process_utils.py:191} INFO -         File "<string>", line 32, in <module>
[2024-10-07T22:09:40.508-0300] {process_utils.py:191} INFO -       RuntimeError: Please install package apache-*** instead of ***
[2024-10-07T22:09:40.508-0300] {process_utils.py:191} INFO -       [end of output]
[2024-10-07T22:09:40.509-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:40.509-0300] {process_utils.py:191} INFO -   note: This error originates from a subprocess, and is likely not a problem with pip.
[2024-10-07T22:09:40.653-0300] {process_utils.py:191} INFO - error: subprocess-exited-with-error
[2024-10-07T22:09:40.654-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:40.655-0300] {process_utils.py:191} INFO - × Getting requirements to build wheel did not run successfully.
[2024-10-07T22:09:40.655-0300] {process_utils.py:191} INFO - │ exit code: 1
[2024-10-07T22:09:40.656-0300] {process_utils.py:191} INFO - ╰─> See above for output.
[2024-10-07T22:09:40.656-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:40.657-0300] {process_utils.py:191} INFO - note: This error originates from a subprocess, and is likely not a problem with pip.
[2024-10-07T22:09:40.792-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T22:09:40.793-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 757, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 669, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvjs4b4_r6/bin/pip', 'install', '-r', '/tmp/venvjs4b4_r6/requirements.txt']' returned non-zero exit status 1.
[2024-10-07T22:09:40.804-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T01:09:21.917101+00:00, execution_date=20241008T010921, start_date=20241008T010935, end_date=20241008T010940
[2024-10-07T22:09:40.818-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task preprocess (Command '['/tmp/venvjs4b4_r6/bin/pip', 'install', '-r', '/tmp/venvjs4b4_r6/requirements.txt']' returned non-zero exit status 1.; 2150)
[2024-10-07T22:09:40.849-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T22:09:40.873-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T22:09:40.878-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
