[2024-10-07T22:09:23.245-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T22:09:23.270-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T01:09:21.917101+00:00 [queued]>
[2024-10-07T22:09:23.281-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T01:09:21.917101+00:00 [queued]>
[2024-10-07T22:09:23.282-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-07T22:09:23.298-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocess> on 2024-10-08 01:09:21.917101+00:00
[2024-10-07T22:09:23.305-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T22:09:23.306-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T01:09:21.917101+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpm43bs947']
[2024-10-07T22:09:23.307-0300] {standard_task_runner.py:63} INFO - Started process 2109 to run task
[2024-10-07T22:09:23.308-0300] {standard_task_runner.py:91} INFO - Job 57: Subtask preprocess
[2024-10-07T22:09:23.357-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T01:09:21.917101+00:00 [running]> on host 4a07270c49a4
[2024-10-07T22:09:23.458-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T01:09:21.917101+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T01:09:21.917101+00:00'
[2024-10-07T22:09:23.460-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T22:09:23.462-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvu0avw2i5 --python=python
[2024-10-07T22:09:23.464-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T22:09:24.197-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 239ms
[2024-10-07T22:09:24.198-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvu0avw2i5, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T22:09:24.199-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T22:09:24.200-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T22:09:24.201-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T22:09:24.246-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvu0avw2i5/bin/pip install -r /tmp/venvu0avw2i5/requirements.txt
[2024-10-07T22:09:24.249-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T22:09:25.740-0300] {process_utils.py:191} INFO - Collecting *** (from -r /tmp/venvu0avw2i5/requirements.txt (line 1))
[2024-10-07T22:09:25.816-0300] {process_utils.py:191} INFO -   Downloading ***-0.6.tar.gz (1.2 kB)
[2024-10-07T22:09:25.832-0300] {process_utils.py:191} INFO -   Installing build dependencies: started
[2024-10-07T22:09:28.045-0300] {process_utils.py:191} INFO -   Installing build dependencies: finished with status 'done'
[2024-10-07T22:09:28.046-0300] {process_utils.py:191} INFO -   Getting requirements to build wheel: started
[2024-10-07T22:09:28.591-0300] {process_utils.py:191} INFO -   Getting requirements to build wheel: finished with status 'error'
[2024-10-07T22:09:28.596-0300] {process_utils.py:191} INFO -   error: subprocess-exited-with-error
[2024-10-07T22:09:28.597-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:28.598-0300] {process_utils.py:191} INFO -   × Getting requirements to build wheel did not run successfully.
[2024-10-07T22:09:28.599-0300] {process_utils.py:191} INFO -   │ exit code: 1
[2024-10-07T22:09:28.599-0300] {process_utils.py:191} INFO -   ╰─> [26 lines of output]
[2024-10-07T22:09:28.600-0300] {process_utils.py:191} INFO -       running egg_info
[2024-10-07T22:09:28.600-0300] {process_utils.py:191} INFO -       writing ***.egg-info/PKG-INFO
[2024-10-07T22:09:28.601-0300] {process_utils.py:191} INFO -       writing dependency_links to ***.egg-info/dependency_links.txt
[2024-10-07T22:09:28.601-0300] {process_utils.py:191} INFO -       writing top-level names to ***.egg-info/top_level.txt
[2024-10-07T22:09:28.602-0300] {process_utils.py:191} INFO -       reading manifest file '***.egg-info/SOURCES.txt'
[2024-10-07T22:09:28.602-0300] {process_utils.py:191} INFO -       writing manifest file '***.egg-info/SOURCES.txt'
[2024-10-07T22:09:28.603-0300] {process_utils.py:191} INFO -       Traceback (most recent call last):
[2024-10-07T22:09:28.603-0300] {process_utils.py:191} INFO -         File "/tmp/venvu0avw2i5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[2024-10-07T22:09:28.604-0300] {process_utils.py:191} INFO -           main()
[2024-10-07T22:09:28.604-0300] {process_utils.py:191} INFO -         File "/tmp/venvu0avw2i5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[2024-10-07T22:09:28.605-0300] {process_utils.py:191} INFO -           json_out['return_val'] = hook(**hook_input['kwargs'])
[2024-10-07T22:09:28.605-0300] {process_utils.py:191} INFO -                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T22:09:28.606-0300] {process_utils.py:191} INFO -         File "/tmp/venvu0avw2i5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[2024-10-07T22:09:28.607-0300] {process_utils.py:191} INFO -           return hook(config_settings)
[2024-10-07T22:09:28.608-0300] {process_utils.py:191} INFO -                  ^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T22:09:28.608-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-zn37fb6o/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
[2024-10-07T22:09:28.609-0300] {process_utils.py:191} INFO -           return self._get_build_requires(config_settings, requirements=[])
[2024-10-07T22:09:28.609-0300] {process_utils.py:191} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T22:09:28.610-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-zn37fb6o/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
[2024-10-07T22:09:28.610-0300] {process_utils.py:191} INFO -           self.run_setup()
[2024-10-07T22:09:28.611-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-zn37fb6o/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
[2024-10-07T22:09:28.611-0300] {process_utils.py:191} INFO -           super().run_setup(setup_script=setup_script)
[2024-10-07T22:09:28.612-0300] {process_utils.py:191} INFO -         File "/tmp/pip-build-env-zn37fb6o/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
[2024-10-07T22:09:28.613-0300] {process_utils.py:191} INFO -           exec(code, locals())
[2024-10-07T22:09:28.613-0300] {process_utils.py:191} INFO -         File "<string>", line 32, in <module>
[2024-10-07T22:09:28.614-0300] {process_utils.py:191} INFO -       RuntimeError: Please install package apache-*** instead of ***
[2024-10-07T22:09:28.615-0300] {process_utils.py:191} INFO -       [end of output]
[2024-10-07T22:09:28.615-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:28.616-0300] {process_utils.py:191} INFO -   note: This error originates from a subprocess, and is likely not a problem with pip.
[2024-10-07T22:09:28.764-0300] {process_utils.py:191} INFO - error: subprocess-exited-with-error
[2024-10-07T22:09:28.765-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:28.766-0300] {process_utils.py:191} INFO - × Getting requirements to build wheel did not run successfully.
[2024-10-07T22:09:28.767-0300] {process_utils.py:191} INFO - │ exit code: 1
[2024-10-07T22:09:28.768-0300] {process_utils.py:191} INFO - ╰─> See above for output.
[2024-10-07T22:09:28.768-0300] {process_utils.py:191} INFO - 
[2024-10-07T22:09:28.769-0300] {process_utils.py:191} INFO - note: This error originates from a subprocess, and is likely not a problem with pip.
[2024-10-07T22:09:28.897-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T22:09:28.898-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 757, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 669, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvu0avw2i5/bin/pip', 'install', '-r', '/tmp/venvu0avw2i5/requirements.txt']' returned non-zero exit status 1.
[2024-10-07T22:09:28.910-0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T01:09:21.917101+00:00, execution_date=20241008T010921, start_date=20241008T010923, end_date=20241008T010928
[2024-10-07T22:09:28.925-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task preprocess (Command '['/tmp/venvu0avw2i5/bin/pip', 'install', '-r', '/tmp/venvu0avw2i5/requirements.txt']' returned non-zero exit status 1.; 2109)
[2024-10-07T22:09:28.948-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T22:09:28.976-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T22:09:28.979-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
